### ISSUE TITLE
elementsPlacementStrategy option is not applying

### ISSUE THREAD

**Issue by Nebules** [adammertel/Leaflet.MarkerCluster.PlacementStrategies#2]
This is a great plugin for me if I can get it to work with my marker icons.  The code below includes your example option settings in the markerclustergroup, and the code for generating the markres. While some options (e.g. spiderLegPolylineOptions) work, elementsPlacementStrategy isn't having an effect. Any ideas?

var herring = L.markerClusterGroup({
	spiderLegPolylineOptions: {weight: 0},
	clockHelpingCircleOptions: {weight: .7, opacity: 1, color: 'black', fillOpacity: 0, dashArray: '10 5'},
	elementsPlacementStrategy: 'concentric',
	helpingCircles: true,
	spiderfyDistanceSurplus: 1,
	spiderfyDistanceMultiplier: 1,
	elementsMultiplier: 1.4,
	firstCircleElements: 5	
});	  

$.getJSON("https://"+cartoDBUserName+".cartodb.com/api/v2/sql?format=GeoJSON&q="+sqlQueryHerring, function(data) {
	geoJsonherring = L.geoJson(data, {
		onEachFeature: function (feature, layer) {
			layer.bindPopup("<p>"+feature.properties.tag_number+"</p>");				
			layer.on('mouseover', function(e) {
				this.openPopup();
				showRoute(feature.properties.tag_number);
			});
			layer.on('mouseout', function(e) {
				this.closePopup();
				map.removeLayer(thisHerringRouteLine);
			});
		}, pointToLayer: function (feature, latlng) {
			var marker = L.marker(latlng,{icon: herringIcon});
			return marker;
		}, pane: 'herring'
	});
	herring.addLayer(geoJsonherring);
});

**Comment by adammertel** [comment]
Hi Nebulus, sorry for such a late answer. 
I tried to replicate your example (https://codepen.io/adammertel/pen/wmEYPg) and the problem I found is the value of the **spiderfyDistanceSurplus** option - it represents the distance between cluster circles. You should set a number at least bigger than 15, the default is 30.

**Comment by adammertel** [comment]
Issue closed due to inactivity
