### ISSUE TITLE
Cluster doesn't remember updated marker classes

### ISSUE THREAD

**Issue by nikitalpopov** [adammertel/Leaflet.MarkerCluster.PlacementStrategies#4]
Cluster doesn't remember updated classes of markers inside it. This problem appears only with this plugin. Example videos:

[Behaviour without PlacementStrategies](https://i.gyazo.com/4b42bc06fada44a8e9a8c1bdd620000b.mp4)
[Behaviour with PlacementStrategies](https://i.gyazo.com/061cde58d8c872b8f2f66f0488f40a14.mp4)  

On marker click its classList updates with new class which should remain until next click on marker. This works fine until plugin is enabled. Each interaction with map after markerclick resets its classList to initial state

**Comment by 128keaton** [comment]
Having this exact same problem!

**Comment by adammertel** [comment]
Guys, thank you very much for reporting this and sorry for such a bad response time.
In my original code, I made an extra effort to set the new class to "spiderfied" markers - but the method was too strick and unflexible and caused the problem you reported. 
I refactored the code and add a new option `spiderfiedClassName` that can be assigned to add this extra class to already spiderfied markers.

It should be working now. But as I am not able to fully reproduce your code, I will let this issue open for now. If you can find some time, please let me know...

The specific part of code is now changed to:
```
if (options.spiderfiedClassName) {
  for (var chmi in childMarkers) {
    const marker = childMarkers[chmi];

    // marker
    if (marker.getIcon) {
      const icon = marker.getIcon();
      if (icon) {
        if (icon.options.className) {
          if (!icon.options.className.includes(options.spiderfiedClassName)) {
            icon.options.className += ' ' + options.spiderfiedClassName;
          }
        } else {
          icon.options.className = options.spiderfiedClassName;
        }
      }

      //circleMarker
    } else if (childMarkers[chmi].setStyle) {
      const classNames = childMarkers[chmi].options.className;
      childMarkers[chmi].setStyle({ className: classNames + ' ' + options.spiderfiedClassName });
    }
  }
}
```

Adam
