### ISSUE TITLE
Helping circles aren't cleared when zooming and spiderfying at the same time 

### ISSUE THREAD

**Issue by scdev0** [adammertel/Leaflet.MarkerCluster.PlacementStrategies#5]
This issue occurs when you zoom and spiderfy by clicking the cluster at the same time really fast.
![Screen Shot 2020-01-22 at 3 24 24 PM](https://user-images.githubusercontent.com/28826596/72957452-9ba37100-3d71-11ea-9edb-e5aa892e9a52.png)
This is because it triggers the `_noanimationUnspiderfy` function in leaflet.markercluster

```
_noanimationUnspiderfy: function () {
	        if (this._spiderfied) {
			this._spiderfied._noanimationUnspiderfy();
		}
	},
```

instead of `_unspiderfyWrapper` or `_unspiderfy` that calls the `unspiderfy` function in this plugin.
Changing the line `this._spiderfied._noanimationUnspiderfy();` in the above function to `this._unspiderfy();` will fix it but perhaps there's a better way to fix it as part of this plugin?

**Comment by adammertel** [comment]
Hello.
Thank you very much for reporting this. I experienced the same problem but was not able to reproduce it. 
I was looking for a more elegant solution but your idea looks the shortest, so I applied a very similar fix to what you proposed.

```
L.MarkerClusterGroup.include({
	_noanimationUnspiderfy: function() {
		if (this._spiderfied) {
			//this._spiderfied._noanimationUnspiderfy();
			this._spiderfied.unspiderfy();
		}
	}
});
```

Adam
